"""empty message

Revision ID: 997103d9e41f
Revises: d776f1839fc7
Create Date: 2025-04-09 23:38:34.950526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997103d9e41f'
down_revision = 'd776f1839fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite__planet')
    # ### end Alembic commands ###
